DEFAULT:
  dataset: cifar10
  ckpt:
  cleantrain: True
  advtrain: False
  advtest: False

Network:
  epochs: 201
  model: ALIF
  tau_v: 5
  ckpt_v: ./spikedata/cifar10/cifar10.pt
  batch_size: 64
  lr: 0.0005
  is_bn: True
  save_target: False
  n_steps: 5
  dataset: "CIFAR10"
  data_path: ./datasets/cifar10
  mean: 0.4734
  std: 0.2009
  loss: "kernel"
  n_class: 10
  tau_m: 5
  tau_s: 3

ATTACK:
  strength: [8/255]
  train: [2/255]
  ft_method: fgm

Layers:
  conv_1:
    type: "conv"
    in_channels: 3
    out_channels: 128
    kernel_size: 3
    padding: 1
    weight_scale: 5
    threshold: 1

  dropout_1:
    type: "dropout"
    p: 0.2

  conv_2:
    type: "conv"
    in_channels: 128
    out_channels: 256
    kernel_size: 3
    padding: 1
    weight_scale: 5
    threshold: 1

  pooling_1:
    type: "pooling"
    kernel_size: 2
    threshold: 0.5

  dropout_2:
    type: "dropout"
    p: 0.2

  conv_3:
    type: "conv"
    in_channels: 256
    out_channels: 512
    kernel_size: 3
    padding: 1
    weight_scale: 5
    threshold: 1

  pooling_2:
    type: "pooling"
    kernel_size: 2
    threshold: 0.5
    
  dropout_3:
    type: "dropout"
    p: 0.2

  conv_4:
    type: "conv"
    in_channels: 512
    out_channels: 1024
    kernel_size: 3
    padding: 1
    weight_scale: 5
    threshold: 1

  dropout_4:
    type: "dropout"
    p: 0.2

  conv_5:
    type: "conv"
    in_channels: 1024
    out_channels: 512
    kernel_size: 3
    padding: 1
    weight_scale: 5
    threshold: 1

  dropout_5:
    type: "dropout"
    p: 0.2

  FC_1:
    type: "linear"
    n_inputs: 32768
    n_outputs: 1024
    weight_scale: 1
    threshold: 1

  dropout_6:
    type: "dropout"
    p: 0.2

  FC_2:
    type: "linear"
    n_inputs: 1024
    n_outputs: 512
    weight_scale: 1
    threshold: 1

  dropout_7:
    type: "dropout"
    p: 0.2

  output:
    type: "linear"
    n_inputs: 512
    n_outputs: 10
    weight_scale: 1
    threshold: 1